# Generated by Django 5.2.7 on 2025-10-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_age_alter_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('mentee', 'Mentee (Student)'), ('mentor', 'Mentor (Professional)')], default='mentee', help_text='Choose whether you are a Mentee (seeking guidance) or Mentor (providing guidance)', max_length=10),
        ),
    ]
