# Generated by Django 5.2.7 on 2025-11-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customuser_gender_pendingsignup_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_skill_level',
            field=models.CharField(blank=True, help_text='e.g. Beginner, Intermediate, Advanced (for mentees).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available_for_mentoring',
            field=models.BooleanField(default=True, help_text="If checked, you will appear in 'Find a Mentor' results."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_seeking_mentorship',
            field=models.BooleanField(default=True, help_text="If checked, you will appear in 'View Mentees' results."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_goals',
            field=models.TextField(blank=True, help_text='What you want to learn or achieve (for mentees).', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mentor_availability',
            field=models.CharField(blank=True, help_text='Typical days/times or availability notes (for mentors).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mentor_bio',
            field=models.TextField(blank=True, help_text='Longer biography or introduction (for mentors).', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mentor_expertise',
            field=models.TextField(blank=True, help_text='Short description of your domains of expertise (for mentors).', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subjects_interested_in',
            field=models.TextField(blank=True, help_text='Subjects or topics where you want mentorship (for mentees).', null=True),
        ),
    ]
