# Generated by Django 5.2.7 on 2026-01-21 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_current_skill_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Mentoring Session', 'verbose_name_plural': 'Mentoring Sessions'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='session',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.AddField(
            model_name='session',
            name='flexibility_comments',
            field=models.TextField(blank=True, help_text="e.g., 'I can start 30 mins before or after the given time.'"),
        ),
        migrations.AddField(
            model_name='session',
            name='initiator',
            field=models.ForeignKey(blank=True, help_text='The person who created this session entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='nature',
            field=models.CharField(blank=True, choices=[('course', 'Course Guidance'), ('career', 'Career Guidance'), ('general', 'General Guidance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='The person who accepts/books the session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='subject_detail',
            field=models.CharField(blank=True, help_text='Name of Course, Career, or Topic', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the session.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(blank=True, choices=[('request', 'Session Request (by Mentee)'), ('post', 'Session Post (by Mentor)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
