# Generated by Django 5.2.7 on 2026-01-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_customuser_last_activity_customuser_presence_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Paste the Google Meet or Zoom link here.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Indicates if the 15-minute reminder has been sent.'),
        ),
    ]
