# Generated by Django 5.2.7 on 2026-01-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_session_meeting_link_session_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
