# Generated by Django 5.2.7 on 2026-01-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_notification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='session',
            name='reminder_sent',
        ),
    ]
