# Generated by Django 5.2.7 on 2026-01-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_notification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Indicates if the 15-minute reminder has been sent.'),
        ),
    ]
