# Generated by Django 5.2.7 on 2026-01-22 06:08

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notification_link_session_reminder_sent'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of skills/interests.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='session',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
