# Generated by Django 5.2.7 on 2026-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customuser_skills_session_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
