# Generated by Django 6.0.4 on 2026-04-19 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_number_or_iban',
            field=models.CharField(blank=True, help_text='Your bank account number or IBAN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_title',
            field=models.CharField(blank=True, help_text='Official name on your account', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_method',
            field=models.CharField(blank=True, help_text='e.g. Bank Deposit, EasyPaisa, JazzCash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(15, '15 Minutes (Rs. 500)'), (30, '30 Minutes (Rs. 1000)'), (45, '45 Minutes (Rs. 1500)'), (60, '1 Hour (Rs. 2000)'), (75, '1 Hour 15 Mins (Rs. 2500)'), (90, '1 Hour 30 Mins (Rs. 3000)'), (105, '1 Hour 45 Mins (Rs. 3500)'), (120, '2 Hours (Rs. 4000)')], default=15, help_text='Session duration in minutes.'),
        ),
        migrations.AddField(
            model_name='session',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Upload the transaction confirmation screenshot.', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='session',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('submitted', 'Proof Submitted'), ('verified', 'Payment Verified')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
