# Generated by Django 6.0.4 on 2026-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_calendar_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
