# Generated by Django 6.0.4 on 2026-05-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_customuser_is_calendar_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_meeting_link',
            field=models.URLField(blank=True, help_text='Your permanent meeting link (Zoom, Google Meet, etc.)', null=True),
        ),
    ]
