# Generated by Django 6.0.4 on 2026-05-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_customuser_personal_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='actual_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='actual_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_started_early',
            field=models.BooleanField(default=False),
        ),
    ]
