# Generated by Django 5.2.7 on 2026-06-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_faq_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload any screenshots or proof (optional).', null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload any screenshots or proof (optional).', null=True, upload_to='support_attachments/'),
        ),
    ]
